---
- name: Install Apache Web Server
  hosts: all
  become: yes  # Use sudo to run the commands
  tasks:
    - name: Update the apt cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running and enabled on boot
      service:
        name: apache2
        state: started
        enabled: yes
